/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.api;

import com.mastercard.developer.mastercard_loyalty_connect_client.ApiException;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.BusinessPartnerStoreDetails;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.BusinessPartnerStoreResponse;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BusinessPartnerStoresApi
 */
@Ignore
public class BusinessPartnerStoresApiTest {

    private final BusinessPartnerStoresApi api = new BusinessPartnerStoresApi();

    
    /**
     * Store company location details
     *
     * Store a company location into Mastercard Loyalty Connect (MLC)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdateBusinessPartnerLocationsTest() throws ApiException {
        BusinessPartnerStoreDetails businessPartnerStoreDetails = null;
        BusinessPartnerStoreResponse response = api.createOrUpdateBusinessPartnerLocations(businessPartnerStoreDetails);

        // TODO: test validations
    }
    
}
