/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.api;

import com.mastercard.developer.mastercard_loyalty_connect_client.ApiException;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.BusinessPartnerLocationDetails;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.BusinessPartnerLocationsResponse;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.Error;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.ServiceUnAvailableError;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.UnauthAccessError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BusinessPartnerLocationsApi
 */
@Ignore
public class BusinessPartnerLocationsApiTest {

    private final BusinessPartnerLocationsApi api = new BusinessPartnerLocationsApi();

    
    /**
     * Store company location details
     *
     * Store a company location into Mastercard Loyalty Connect (MLC)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdateBusinessPartnerLocationsTest() throws ApiException {
        String locationId = null;
        String terminalId = null;
        BusinessPartnerLocationDetails businessPartnerLocationDetails = null;
        BusinessPartnerLocationsResponse response = api.createOrUpdateBusinessPartnerLocations(locationId, terminalId, businessPartnerLocationDetails);

        // TODO: test validations
    }
    
}
