/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BusinessPartnerLocationDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-30T11:15:32.100+05:30[Asia/Calcutta]")
public class BusinessPartnerLocationDetails {
  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_ICA_NUMBER = "icaNumber";
  @SerializedName(SERIALIZED_NAME_ICA_NUMBER)
  private String icaNumber;

  public static final String SERIALIZED_NAME_STORE_EMAIL = "storeEmail";
  @SerializedName(SERIALIZED_NAME_STORE_EMAIL)
  private String storeEmail;

  public static final String SERIALIZED_NAME_STORE_NAME = "storeName";
  @SerializedName(SERIALIZED_NAME_STORE_NAME)
  private String storeName;

  public static final String SERIALIZED_NAME_STORE_PHONE = "storePhone";
  @SerializedName(SERIALIZED_NAME_STORE_PHONE)
  private String storePhone;

  public static final String SERIALIZED_NAME_STORE_TYPE = "storeType";
  @SerializedName(SERIALIZED_NAME_STORE_TYPE)
  private String storeType;

  public static final String SERIALIZED_NAME_VAT_NUMBER = "vatNumber";
  @SerializedName(SERIALIZED_NAME_VAT_NUMBER)
  private String vatNumber;


  public BusinessPartnerLocationDetails addressLine1(String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Address description
   * @return addressLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1 Notting Hill High Street", value = "Address description")

  public String getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public BusinessPartnerLocationDetails addressLine2(String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Address description
   * @return addressLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "London, W11 1AB", value = "Address description")

  public String getAddressLine2() {
    return addressLine2;
  }


  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public BusinessPartnerLocationDetails country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UK", value = "Country")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public BusinessPartnerLocationDetails icaNumber(String icaNumber) {
    
    this.icaNumber = icaNumber;
    return this;
  }

   /**
   * Business partner Code associated with payment terminal.
   * @return icaNumber
  **/
  @ApiModelProperty(example = "234214", required = true, value = "Business partner Code associated with payment terminal.")

  public String getIcaNumber() {
    return icaNumber;
  }


  public void setIcaNumber(String icaNumber) {
    this.icaNumber = icaNumber;
  }


  public BusinessPartnerLocationDetails storeEmail(String storeEmail) {
    
    this.storeEmail = storeEmail;
    return this;
  }

   /**
   * Valid email address
   * @return storeEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "jsmith@mastercard.com", value = "Valid email address")

  public String getStoreEmail() {
    return storeEmail;
  }


  public void setStoreEmail(String storeEmail) {
    this.storeEmail = storeEmail;
  }


  public BusinessPartnerLocationDetails storeName(String storeName) {
    
    this.storeName = storeName;
    return this;
  }

   /**
   * Store Name of Business partner Code associated with payment terminal.
   * @return storeName
  **/
  @ApiModelProperty(example = "Liberty Store", required = true, value = "Store Name of Business partner Code associated with payment terminal.")

  public String getStoreName() {
    return storeName;
  }


  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }


  public BusinessPartnerLocationDetails storePhone(String storePhone) {
    
    this.storePhone = storePhone;
    return this;
  }

   /**
   * Valid mobile phone number
   * @return storePhone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+44 (0) 7970 225 256", value = "Valid mobile phone number")

  public String getStorePhone() {
    return storePhone;
  }


  public void setStorePhone(String storePhone) {
    this.storePhone = storePhone;
  }


  public BusinessPartnerLocationDetails storeType(String storeType) {
    
    this.storeType = storeType;
    return this;
  }

   /**
   * Store Type
   * @return storeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "full-price", value = "Store Type")

  public String getStoreType() {
    return storeType;
  }


  public void setStoreType(String storeType) {
    this.storeType = storeType;
  }


  public BusinessPartnerLocationDetails vatNumber(String vatNumber) {
    
    this.vatNumber = vatNumber;
    return this;
  }

   /**
   * VAT number
   * @return vatNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GB 8978654", value = "VAT number")

  public String getVatNumber() {
    return vatNumber;
  }


  public void setVatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessPartnerLocationDetails businessPartnerLocationDetails = (BusinessPartnerLocationDetails) o;
    return Objects.equals(this.addressLine1, businessPartnerLocationDetails.addressLine1) &&
        Objects.equals(this.addressLine2, businessPartnerLocationDetails.addressLine2) &&
        Objects.equals(this.country, businessPartnerLocationDetails.country) &&
        Objects.equals(this.icaNumber, businessPartnerLocationDetails.icaNumber) &&
        Objects.equals(this.storeEmail, businessPartnerLocationDetails.storeEmail) &&
        Objects.equals(this.storeName, businessPartnerLocationDetails.storeName) &&
        Objects.equals(this.storePhone, businessPartnerLocationDetails.storePhone) &&
        Objects.equals(this.storeType, businessPartnerLocationDetails.storeType) &&
        Objects.equals(this.vatNumber, businessPartnerLocationDetails.vatNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressLine1, addressLine2, country, icaNumber, storeEmail, storeName, storePhone, storeType, vatNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessPartnerLocationDetails {\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    icaNumber: ").append(toIndentedString(icaNumber)).append("\n");
    sb.append("    storeEmail: ").append(toIndentedString(storeEmail)).append("\n");
    sb.append("    storeName: ").append(toIndentedString(storeName)).append("\n");
    sb.append("    storePhone: ").append(toIndentedString(storePhone)).append("\n");
    sb.append("    storeType: ").append(toIndentedString(storeType)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

