/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BusinessPartnerLocationsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-30T11:15:32.100+05:30[Asia/Calcutta]")
public class BusinessPartnerLocationsResponse {
  public static final String SERIALIZED_NAME_LOCATION_ID = "locationId";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private String locationId;

  public static final String SERIALIZED_NAME_LOCATION_REFERENCE_ID = "locationReferenceId";
  @SerializedName(SERIALIZED_NAME_LOCATION_REFERENCE_ID)
  private String locationReferenceId;

  public static final String SERIALIZED_NAME_TERMINAL_ID = "terminalId";
  @SerializedName(SERIALIZED_NAME_TERMINAL_ID)
  private String terminalId;


  public BusinessPartnerLocationsResponse locationId(String locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * BusinessPartnerLocationDetails Identity
   * @return locationId
  **/
  @ApiModelProperty(example = "G3243423J4534", required = true, value = "BusinessPartnerLocationDetails Identity")

  public String getLocationId() {
    return locationId;
  }


  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }


  public BusinessPartnerLocationsResponse locationReferenceId(String locationReferenceId) {
    
    this.locationReferenceId = locationReferenceId;
    return this;
  }

   /**
   * Unique reference key for business partner location
   * @return locationReferenceId
  **/
  @ApiModelProperty(example = "5f0d07c1-6fc4-4e74-9152-0e20bb767589", required = true, value = "Unique reference key for business partner location")

  public String getLocationReferenceId() {
    return locationReferenceId;
  }


  public void setLocationReferenceId(String locationReferenceId) {
    this.locationReferenceId = locationReferenceId;
  }


  public BusinessPartnerLocationsResponse terminalId(String terminalId) {
    
    this.terminalId = terminalId;
    return this;
  }

   /**
   * Terminal Identity
   * @return terminalId
  **/
  @ApiModelProperty(example = "K42398732L3292", required = true, value = "Terminal Identity")

  public String getTerminalId() {
    return terminalId;
  }


  public void setTerminalId(String terminalId) {
    this.terminalId = terminalId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessPartnerLocationsResponse businessPartnerLocationsResponse = (BusinessPartnerLocationsResponse) o;
    return Objects.equals(this.locationId, businessPartnerLocationsResponse.locationId) &&
        Objects.equals(this.locationReferenceId, businessPartnerLocationsResponse.locationReferenceId) &&
        Objects.equals(this.terminalId, businessPartnerLocationsResponse.terminalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationId, locationReferenceId, terminalId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessPartnerLocationsResponse {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationReferenceId: ").append(toIndentedString(locationReferenceId)).append("\n");
    sb.append("    terminalId: ").append(toIndentedString(terminalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

