/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Datetime
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T19:05:09.264+05:30[Asia/Calcutta]")
public class Datetime {
    public static final String SERIALIZED_NAME_UTC = "utc";
    public static final String SERIALIZED_NAME_LOCAL = "local";
    @SerializedName(SERIALIZED_NAME_UTC)
    private Long utc;
    @SerializedName(SERIALIZED_NAME_LOCAL)
    private OffsetDateTime local;


    public Datetime utc(Long utc) {

        this.utc = utc;
        return this;
    }

    /**
     * utc associated with date time of business partner or it&#39;s store
     *
     * @return utc
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "utc associated with date time of business partner or it's store")

    public Long getUtc() {
        return utc;
    }


    public void setUtc(Long utc) {
        this.utc = utc;
    }


    public Datetime local(OffsetDateTime local) {

        this.local = local;
        return this;
    }

    /**
     * local with date time of business partner or it&#39;s store
     *
     * @return local
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "local with date time of business partner or it's store")

    public OffsetDateTime getLocal() {
        return local;
    }


    public void setLocal(OffsetDateTime local) {
        this.local = local;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Datetime datetime = (Datetime) o;
        return Objects.equals(this.utc, datetime.utc) &&
                Objects.equals(this.local, datetime.local);
    }

    @Override
    public int hashCode() {
        return Objects.hash(utc, local);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Datetime {\n");
        sb.append("    utc: ").append(toIndentedString(utc)).append("\n");
        sb.append("    local: ").append(toIndentedString(local)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

