/*
 * Mastercard Loyalty Connect Service
 * Rest Service for linking payment cards with loyalty programme
 *
 * OpenAPI spec version: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EnrollLoyaltyConnectResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-16T15:13:26.840+05:30[Asia/Calcutta]")
public class EnrollLoyaltyConnectResponse {
  public static final String SERIALIZED_NAME_LOYALTY_CONNECT_REFERENCE_ID = "loyaltyConnectReferenceId";
  @SerializedName(SERIALIZED_NAME_LOYALTY_CONNECT_REFERENCE_ID)
  private String loyaltyConnectReferenceId;

  public EnrollLoyaltyConnectResponse loyaltyConnectReferenceId(String loyaltyConnectReferenceId) {
    this.loyaltyConnectReferenceId = loyaltyConnectReferenceId;
    return this;
  }

   /**
   * Unique reference key for the connection of a loyalty ID and payment card
   * @return loyaltyConnectReferenceId
  **/
  @ApiModelProperty(example = "f962ad86-d408-467c-8b74-14983569d36c", required = true, value = "Unique reference key for the connection of a loyalty ID and payment card")
  public String getLoyaltyConnectReferenceId() {
    return loyaltyConnectReferenceId;
  }

  public void setLoyaltyConnectReferenceId(String loyaltyConnectReferenceId) {
    this.loyaltyConnectReferenceId = loyaltyConnectReferenceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrollLoyaltyConnectResponse enrollLoyaltyConnectResponse = (EnrollLoyaltyConnectResponse) o;
    return Objects.equals(this.loyaltyConnectReferenceId, enrollLoyaltyConnectResponse.loyaltyConnectReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loyaltyConnectReferenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrollLoyaltyConnectResponse {\n");
    
    sb.append("    loyaltyConnectReferenceId: ").append(toIndentedString(loyaltyConnectReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

