/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Key
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T19:05:09.264+05:30[Asia/Calcutta]")
public class Key {
    public static final String SERIALIZED_NAME_APPLICATION = "application";
    public static final String SERIALIZED_NAME_URLSAFE = "urlsafe";
    public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
    public static final String SERIALIZED_NAME_PATHS = "paths";
    @SerializedName(SERIALIZED_NAME_APPLICATION)
    private String application;
    @SerializedName(SERIALIZED_NAME_URLSAFE)
    private String urlsafe;
    @SerializedName(SERIALIZED_NAME_NAMESPACE)
    private String namespace;
    @SerializedName(SERIALIZED_NAME_PATHS)
    private List<Path> paths = null;


    public Key application(String application) {

        this.application = application;
        return this;
    }

    /**
     * application associated with business partner or it&#39;s store
     *
     * @return application
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "e~yreceipts-prod-uk", value = "application associated with business partner or it's store")

    public String getApplication() {
        return application;
    }


    public void setApplication(String application) {
        this.application = application;
    }


    public Key urlsafe(String urlsafe) {

        this.urlsafe = urlsafe;
        return this;
    }

    /**
     * urlsafe associated with business partner or it&#39;s store
     *
     * @return urlsafe
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "ahNlfnlyZWNlaXB0cy1wcm9kLXVrch0LEhBCdXNpbmVzc0xvY2F0aW9uGICAwNXo_uoKDA", value = "urlsafe associated with business partner or it's store")

    public String getUrlsafe() {
        return urlsafe;
    }


    public void setUrlsafe(String urlsafe) {
        this.urlsafe = urlsafe;
    }


    public Key namespace(String namespace) {

        this.namespace = namespace;
        return this;
    }

    /**
     * namespace associated with business partner or it&#39;s store
     *
     * @return namespace
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "namespace", value = "namespace associated with business partner or it's store")

    public String getNamespace() {
        return namespace;
    }


    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }


    public Key paths(List<Path> paths) {

        this.paths = paths;
        return this;
    }

    public Key addPathsItem(Path pathsItem) {
        if (this.paths == null) {
            this.paths = new ArrayList<Path>();
        }
        this.paths.add(pathsItem);
        return this;
    }

    /**
     * Get paths
     *
     * @return paths
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<Path> getPaths() {
        return paths;
    }


    public void setPaths(List<Path> paths) {
        this.paths = paths;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Key key = (Key) o;
        return Objects.equals(this.application, key.application) &&
                Objects.equals(this.urlsafe, key.urlsafe) &&
                Objects.equals(this.namespace, key.namespace) &&
                Objects.equals(this.paths, key.paths);
    }

    @Override
    public int hashCode() {
        return Objects.hash(application, urlsafe, namespace, paths);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Key {\n");
        sb.append("    application: ").append(toIndentedString(application)).append("\n");
        sb.append("    urlsafe: ").append(toIndentedString(urlsafe)).append("\n");
        sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
        sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

