/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Member
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-30T11:15:32.100+05:30[Asia/Calcutta]")
public class Member {
  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_ADDRESS_LINE3 = "addressLine3";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE3)
  private String addressLine3;

  public static final String SERIALIZED_NAME_CITY_NAME = "cityName";
  @SerializedName(SERIALIZED_NAME_CITY_NAME)
  private String cityName;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  private String emailAddress;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_MOBILE_PHONE_NUMBER = "mobilePhoneNumber";
  @SerializedName(SERIALIZED_NAME_MOBILE_PHONE_NUMBER)
  private String mobilePhoneNumber;

  public static final String SERIALIZED_NAME_PARTNER_CODE = "partnerCode";
  @SerializedName(SERIALIZED_NAME_PARTNER_CODE)
  private String partnerCode;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_STATE_PROVINCE_CODE = "stateProvinceCode";
  @SerializedName(SERIALIZED_NAME_STATE_PROVINCE_CODE)
  private String stateProvinceCode;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_USER_TYPE = "userType";
  @SerializedName(SERIALIZED_NAME_USER_TYPE)
  private String userType;


  public Member addressLine1(String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Address Line 1 of the Customer&#39;s address
   * @return addressLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10 Upper Bank Street", value = "Address Line 1 of the Customer's address")

  public String getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public Member addressLine2(String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Address Line 2 of the Customer&#39;s address
   * @return addressLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Canary Wharf", value = "Address Line 2 of the Customer's address")

  public String getAddressLine2() {
    return addressLine2;
  }


  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public Member addressLine3(String addressLine3) {
    
    this.addressLine3 = addressLine3;
    return this;
  }

   /**
   * Address Line 3 of the Customer&#39;s address
   * @return addressLine3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Address Line 3 of the Customer's address")

  public String getAddressLine3() {
    return addressLine3;
  }


  public void setAddressLine3(String addressLine3) {
    this.addressLine3 = addressLine3;
  }


  public Member cityName(String cityName) {
    
    this.cityName = cityName;
    return this;
  }

   /**
   * City name as per Customer&#39;s address
   * @return cityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "London", value = "City name as per Customer's address")

  public String getCityName() {
    return cityName;
  }


  public void setCityName(String cityName) {
    this.cityName = cityName;
  }


  public Member countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Country Code as per Customer&#39;s address
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UK", value = "Country Code as per Customer's address")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public Member emailAddress(String emailAddress) {
    
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Valid email address used by the Customer
   * @return emailAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "jsmith@mastercard.com", value = "Valid email address used by the Customer")

  public String getEmailAddress() {
    return emailAddress;
  }


  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public Member firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Customer&#39;s first name
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "John", value = "Customer's first name")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public Member lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Customer&#39;s last name
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Smith", value = "Customer's last name")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Member mobilePhoneNumber(String mobilePhoneNumber) {
    
    this.mobilePhoneNumber = mobilePhoneNumber;
    return this;
  }

   /**
   * Valid mobile phone number used by the Customer
   * @return mobilePhoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+44 (0) 7911 123 456", value = "Valid mobile phone number used by the Customer")

  public String getMobilePhoneNumber() {
    return mobilePhoneNumber;
  }


  public void setMobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
  }


  public Member partnerCode(String partnerCode) {
    
    this.partnerCode = partnerCode;
    return this;
  }

   /**
   * For every business partner that comes on board with MLC, Mastercard assigns a Interbank Card Association (ICA) Number used to identify that partner. The Partner Code field will receive this ICA Number.
   * @return partnerCode
  **/
  @ApiModelProperty(example = "MLCMerchant", required = true, value = "For every business partner that comes on board with MLC, Mastercard assigns a Interbank Card Association (ICA) Number used to identify that partner. The Partner Code field will receive this ICA Number.")

  public String getPartnerCode() {
    return partnerCode;
  }


  public void setPartnerCode(String partnerCode) {
    this.partnerCode = partnerCode;
  }


  public Member postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal Code as per the Customer&#39;s address
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "E14 5NP", value = "Postal Code as per the Customer's address")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Member stateProvinceCode(String stateProvinceCode) {
    
    this.stateProvinceCode = stateProvinceCode;
    return this;
  }

   /**
   * State Code as per the Customer&#39;s address
   * @return stateProvinceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "State Code as per the Customer's address")

  public String getStateProvinceCode() {
    return stateProvinceCode;
  }


  public void setStateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
  }


  public Member title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Name prefix ( Mr. / Ms. / Mrs. etc )
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Mr.", value = "Name prefix ( Mr. / Ms. / Mrs. etc )")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Member userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Customer Identifier assigned by the business partner (issuer or merchant) to MLC user
   * @return userId
  **/
  @ApiModelProperty(example = "jsmith@mastercard.com", required = true, value = "Customer Identifier assigned by the business partner (issuer or merchant) to MLC user")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public Member userType(String userType) {
    
    this.userType = userType;
    return this;
  }

   /**
   * For Merchant, this value has to be MERCHANT_LOYALTY_ID. For Issuer, this value has to be BANK_CUSTOMER_NUMBER
   * @return userType
  **/
  @ApiModelProperty(example = "MERCHANT_LOYALTY_ID", required = true, value = "For Merchant, this value has to be MERCHANT_LOYALTY_ID. For Issuer, this value has to be BANK_CUSTOMER_NUMBER")

  public String getUserType() {
    return userType;
  }


  public void setUserType(String userType) {
    this.userType = userType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Member member = (Member) o;
    return Objects.equals(this.addressLine1, member.addressLine1) &&
        Objects.equals(this.addressLine2, member.addressLine2) &&
        Objects.equals(this.addressLine3, member.addressLine3) &&
        Objects.equals(this.cityName, member.cityName) &&
        Objects.equals(this.countryCode, member.countryCode) &&
        Objects.equals(this.emailAddress, member.emailAddress) &&
        Objects.equals(this.firstName, member.firstName) &&
        Objects.equals(this.lastName, member.lastName) &&
        Objects.equals(this.mobilePhoneNumber, member.mobilePhoneNumber) &&
        Objects.equals(this.partnerCode, member.partnerCode) &&
        Objects.equals(this.postalCode, member.postalCode) &&
        Objects.equals(this.stateProvinceCode, member.stateProvinceCode) &&
        Objects.equals(this.title, member.title) &&
        Objects.equals(this.userId, member.userId) &&
        Objects.equals(this.userType, member.userType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressLine1, addressLine2, addressLine3, cityName, countryCode, emailAddress, firstName, lastName, mobilePhoneNumber, partnerCode, postalCode, stateProvinceCode, title, userId, userType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Member {\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    addressLine3: ").append(toIndentedString(addressLine3)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    mobilePhoneNumber: ").append(toIndentedString(mobilePhoneNumber)).append("\n");
    sb.append("    partnerCode: ").append(toIndentedString(partnerCode)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    stateProvinceCode: ").append(toIndentedString(stateProvinceCode)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

