/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.MemberMerchantLoyaltyDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MerchantLoyaltyProgramSearchResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T19:05:09.264+05:30[Asia/Calcutta]")
public class MerchantLoyaltyProgramSearchResponse {
  public static final String SERIALIZED_NAME_MEMBER_TOKEN = "memberToken";
  @SerializedName(SERIALIZED_NAME_MEMBER_TOKEN)
  private String memberToken;

  public static final String SERIALIZED_NAME_MEMBER_MERCHANT_LOYALTY_DETAILS = "memberMerchantLoyaltyDetails";
  @SerializedName(SERIALIZED_NAME_MEMBER_MERCHANT_LOYALTY_DETAILS)
  private List<MemberMerchantLoyaltyDetails> memberMerchantLoyaltyDetails = null;


  public MerchantLoyaltyProgramSearchResponse memberToken(String memberToken) {
    
    this.memberToken = memberToken;
    return this;
  }

   /**
   * Unique reference key for a member
   * @return memberToken
  **/
  @ApiModelProperty(example = "kT87TFbPtw6z100047", required = true, value = "Unique reference key for a member")

  public String getMemberToken() {
    return memberToken;
  }


  public void setMemberToken(String memberToken) {
    this.memberToken = memberToken;
  }


  public MerchantLoyaltyProgramSearchResponse memberMerchantLoyaltyDetails(List<MemberMerchantLoyaltyDetails> memberMerchantLoyaltyDetails) {
    
    this.memberMerchantLoyaltyDetails = memberMerchantLoyaltyDetails;
    return this;
  }

  public MerchantLoyaltyProgramSearchResponse addMemberMerchantLoyaltyDetailsItem(MemberMerchantLoyaltyDetails memberMerchantLoyaltyDetailsItem) {
    if (this.memberMerchantLoyaltyDetails == null) {
      this.memberMerchantLoyaltyDetails = new ArrayList<MemberMerchantLoyaltyDetails>();
    }
    this.memberMerchantLoyaltyDetails.add(memberMerchantLoyaltyDetailsItem);
    return this;
  }

   /**
   * Get memberMerchantLoyaltyDetails
   * @return memberMerchantLoyaltyDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<MemberMerchantLoyaltyDetails> getMemberMerchantLoyaltyDetails() {
    return memberMerchantLoyaltyDetails;
  }


  public void setMemberMerchantLoyaltyDetails(List<MemberMerchantLoyaltyDetails> memberMerchantLoyaltyDetails) {
    this.memberMerchantLoyaltyDetails = memberMerchantLoyaltyDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantLoyaltyProgramSearchResponse merchantLoyaltyProgramSearchResponse = (MerchantLoyaltyProgramSearchResponse) o;
    return Objects.equals(this.memberToken, merchantLoyaltyProgramSearchResponse.memberToken) &&
        Objects.equals(this.memberMerchantLoyaltyDetails, merchantLoyaltyProgramSearchResponse.memberMerchantLoyaltyDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberToken, memberMerchantLoyaltyDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantLoyaltyProgramSearchResponse {\n");
    sb.append("    memberToken: ").append(toIndentedString(memberToken)).append("\n");
    sb.append("    memberMerchantLoyaltyDetails: ").append(toIndentedString(memberMerchantLoyaltyDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

