/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.Daytime;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Telephone
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T19:05:09.264+05:30[Asia/Calcutta]")
public class Telephone {
  public static final String SERIALIZED_NAME_DAYTIME = "daytime";
  @SerializedName(SERIALIZED_NAME_DAYTIME)
  private Daytime daytime;


  public Telephone daytime(Daytime daytime) {
    
    this.daytime = daytime;
    return this;
  }

   /**
   * Get daytime
   * @return daytime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Daytime getDaytime() {
    return daytime;
  }


  public void setDaytime(Daytime daytime) {
    this.daytime = daytime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Telephone telephone = (Telephone) o;
    return Objects.equals(this.daytime, telephone.daytime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daytime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Telephone {\n");
    sb.append("    daytime: ").append(toIndentedString(daytime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

