/*
 * Mastercard Loyalty Connect Service
 * Rest Service for linking payment cards with loyalty programme
 *
 * OpenAPI spec version: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Transaction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-16T15:13:26.840+05:30[Asia/Calcutta]")
public class Transaction {
  public static final String SERIALIZED_NAME_BANK_CARD_NUMBER = "bankCardNumber";
  @SerializedName(SERIALIZED_NAME_BANK_CARD_NUMBER)
  private String bankCardNumber;

  public static final String SERIALIZED_NAME_ISSUER_NAME = "issuerName";
  @SerializedName(SERIALIZED_NAME_ISSUER_NAME)
  private String issuerName;

  public static final String SERIALIZED_NAME_IV = "iv";
  @SerializedName(SERIALIZED_NAME_IV)
  private String iv;

  public static final String SERIALIZED_NAME_KSN = "ksn";
  @SerializedName(SERIALIZED_NAME_KSN)
  private String ksn;

  public static final String SERIALIZED_NAME_MERCHANT_LOCATION_ID = "merchantLocationId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_LOCATION_ID)
  private String merchantLocationId;

  public static final String SERIALIZED_NAME_PAYMENT_CARD_NETWORK_DETAILS = "paymentCardNetworkDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_CARD_NETWORK_DETAILS)
  private String paymentCardNetworkDetails;

  public static final String SERIALIZED_NAME_TERMINAL_ID = "terminalId";
  @SerializedName(SERIALIZED_NAME_TERMINAL_ID)
  private String terminalId;

  public Transaction bankCardNumber(String bankCardNumber) {
    this.bankCardNumber = bankCardNumber;
    return this;
  }

   /**
   * Payment Card number that represents a valid card the MLC user wants to connect
   * @return bankCardNumber
  **/
  @ApiModelProperty(example = "000000014B2E3883F0723361900276A1366153731533059120C18075E4B12160232E7BD698D680EEABF32DA23B4FF0B41E116C3FB0C45AA78F0BF21F9A178F5F79EFE80A851F5B575BB56CA7", required = true, value = "Payment Card number that represents a valid card the MLC user wants to connect")
  public String getBankCardNumber() {
    return bankCardNumber;
  }

  public void setBankCardNumber(String bankCardNumber) {
    this.bankCardNumber = bankCardNumber;
  }

  public Transaction issuerName(String issuerName) {
    this.issuerName = issuerName;
    return this;
  }

   /**
   * Name of the issuer
   * @return issuerName
  **/
  @ApiModelProperty(example = "MLCIssuer", value = "Name of the issuer")
  public String getIssuerName() {
    return issuerName;
  }

  public void setIssuerName(String issuerName) {
    this.issuerName = issuerName;
  }

  public Transaction iv(String iv) {
    this.iv = iv;
    return this;
  }

   /**
   * Initial Vector
   * @return iv
  **/
  @ApiModelProperty(example = "0000000000000000", value = "Initial Vector")
  public String getIv() {
    return iv;
  }

  public void setIv(String iv) {
    this.iv = iv;
  }

  public Transaction ksn(String ksn) {
    this.ksn = ksn;
    return this;
  }

   /**
   * Key Serial Number
   * @return ksn
  **/
  @ApiModelProperty(example = "4D43544553A9FAE00008", required = true, value = "Key Serial Number")
  public String getKsn() {
    return ksn;
  }

  public void setKsn(String ksn) {
    this.ksn = ksn;
  }

  public Transaction merchantLocationId(String merchantLocationId) {
    this.merchantLocationId = merchantLocationId;
    return this;
  }

   /**
   * Merchant location id
   * @return merchantLocationId
  **/
  @ApiModelProperty(example = "LOC1001", value = "Merchant location id")
  public String getMerchantLocationId() {
    return merchantLocationId;
  }

  public void setMerchantLocationId(String merchantLocationId) {
    this.merchantLocationId = merchantLocationId;
  }

  public Transaction paymentCardNetworkDetails(String paymentCardNetworkDetails) {
    this.paymentCardNetworkDetails = paymentCardNetworkDetails;
    return this;
  }

   /**
   * Network used for the transaction
   * @return paymentCardNetworkDetails
  **/
  @ApiModelProperty(example = "Mastercard", value = "Network used for the transaction")
  public String getPaymentCardNetworkDetails() {
    return paymentCardNetworkDetails;
  }

  public void setPaymentCardNetworkDetails(String paymentCardNetworkDetails) {
    this.paymentCardNetworkDetails = paymentCardNetworkDetails;
  }

  public Transaction terminalId(String terminalId) {
    this.terminalId = terminalId;
    return this;
  }

   /**
   * Merchant terminal id
   * @return terminalId
  **/
  @ApiModelProperty(example = "MLCMerchant001", value = "Merchant terminal id")
  public String getTerminalId() {
    return terminalId;
  }

  public void setTerminalId(String terminalId) {
    this.terminalId = terminalId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.bankCardNumber, transaction.bankCardNumber) &&
        Objects.equals(this.issuerName, transaction.issuerName) &&
        Objects.equals(this.iv, transaction.iv) &&
        Objects.equals(this.ksn, transaction.ksn) &&
        Objects.equals(this.merchantLocationId, transaction.merchantLocationId) &&
        Objects.equals(this.paymentCardNetworkDetails, transaction.paymentCardNetworkDetails) &&
        Objects.equals(this.terminalId, transaction.terminalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankCardNumber, issuerName, iv, ksn, merchantLocationId, paymentCardNetworkDetails, terminalId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    bankCardNumber: ").append(toIndentedString(bankCardNumber)).append("\n");
    sb.append("    issuerName: ").append(toIndentedString(issuerName)).append("\n");
    sb.append("    iv: ").append(toIndentedString(iv)).append("\n");
    sb.append("    ksn: ").append(toIndentedString(ksn)).append("\n");
    sb.append("    merchantLocationId: ").append(toIndentedString(merchantLocationId)).append("\n");
    sb.append("    paymentCardNetworkDetails: ").append(toIndentedString(paymentCardNetworkDetails)).append("\n");
    sb.append("    terminalId: ").append(toIndentedString(terminalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

