/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.LoyaltyConnectResponse;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.MemberMerchantLoyaltyDetails;
import com.mastercard.developer.mastercard_loyalty_connect_client.model.PaymentCardDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MemberResponse
 */
public class MemberResponseTest {
    private final MemberResponse model = new MemberResponse();

    /**
     * Model tests for MemberResponse
     */
    @Test
    public void testMemberResponse() {
        // TODO: test MemberResponse
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'addressLine3'
     */
    @Test
    public void addressLine3Test() {
        // TODO: test addressLine3
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'loyaltyConnectResponses'
     */
    @Test
    public void loyaltyConnectResponsesTest() {
        // TODO: test loyaltyConnectResponses
    }

    /**
     * Test the property 'memberReferenceId'
     */
    @Test
    public void memberReferenceIdTest() {
        // TODO: test memberReferenceId
    }

    /**
     * Test the property 'merchantLoyaltyDetails'
     */
    @Test
    public void merchantLoyaltyDetailsTest() {
        // TODO: test merchantLoyaltyDetails
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    public void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

    /**
     * Test the property 'paymentCards'
     */
    @Test
    public void paymentCardsTest() {
        // TODO: test paymentCards
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'stateProvinceCode'
     */
    @Test
    public void stateProvinceCodeTest() {
        // TODO: test stateProvinceCode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
