/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MemberRefIdErrorItem
 */
public class MemberRefIdErrorItemTest {
    private final MemberRefIdErrorItem model = new MemberRefIdErrorItem();

    /**
     * Model tests for MemberRefIdErrorItem
     */
    @Test
    public void testMemberRefIdErrorItem() {
        // TODO: test MemberRefIdErrorItem
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'recoverable'
     */
    @Test
    public void recoverableTest() {
        // TODO: test recoverable
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

}
