/*
 * Mastercard Loyalty Connect Service
 * Rest Service for connecting payment cards with loyalty programs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionResponse
 */
public class TransactionResponseTest {
    private final TransactionResponse model = new TransactionResponse();

    /**
     * Model tests for TransactionResponse
     */
    @Test
    public void testTransactionResponse() {
        // TODO: test TransactionResponse
    }

    /**
     * Test the property 'loyaltyId'
     */
    @Test
    public void loyaltyIdTest() {
        // TODO: test loyaltyId
    }

}
