/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessPartnerStoreResponse
 */
public class BusinessPartnerStoreResponseTest {
    private final BusinessPartnerStoreResponse model = new BusinessPartnerStoreResponse();

    /**
     * Model tests for BusinessPartnerStoreResponse
     */
    @Test
    public void testBusinessPartnerStoreResponse() {
        // TODO: test BusinessPartnerStoreResponse
    }

    /**
     * Test the property 'businessPartnerStoreId'
     */
    @Test
    public void businessPartnerStoreIdTest() {
        // TODO: test businessPartnerStoreId
    }

    /**
     * Test the property 'storeReferenceId'
     */
    @Test
    public void storeReferenceIdTest() {
        // TODO: test storeReferenceId
    }

}
