/*
 * Mastercard Loyalty Connect Service
 * Connecting payment and retail loyalty into a single checkout experience
 *
 * The version of the OpenAPI document: 2.2.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_connect_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LoyaltyConnect
 */
public class LoyaltyConnectTest {
    private final LoyaltyConnect model = new LoyaltyConnect();

    /**
     * Model tests for LoyaltyConnect
     */
    @Test
    public void testLoyaltyConnect() {
        // TODO: test LoyaltyConnect
    }

    /**
     * Test the property 'paymentCardReferenceId'
     */
    @Test
    public void paymentCardReferenceIdTest() {
        // TODO: test paymentCardReferenceId
    }

    /**
     * Test the property 'memberMerchantReferenceId'
     */
    @Test
    public void memberMerchantReferenceIdTest() {
        // TODO: test memberMerchantReferenceId
    }

}
