
/*
 * Copyright 2016 MasterCard International.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 * Neither the name of the MasterCard International Incorporated nor the names of its
 * contributors may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */
/*
 * Mastercard Loyalty Connect Service
 * Rest Service for linking payment cards with loyalty programme
 *
 * OpenAPI spec version: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EnrollLoyaltyConnectResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-12T16:02:42.822+05:30[Asia/Calcutta]")
public class EnrollLoyaltyConnectResponse {
  public static final String SERIALIZED_NAME_LOYALTY_CONNECT_REFERENCE_ID = "loyaltyConnectReferenceId";
  @SerializedName(SERIALIZED_NAME_LOYALTY_CONNECT_REFERENCE_ID)
  private String loyaltyConnectReferenceId;

  public EnrollLoyaltyConnectResponse loyaltyConnectReferenceId(String loyaltyConnectReferenceId) {
    this.loyaltyConnectReferenceId = loyaltyConnectReferenceId;
    return this;
  }

   /**
   * Unique reference key for the connection of a loyalty ID and payment card
   * @return loyaltyConnectReferenceId
  **/
  @ApiModelProperty(example = "f962ad86-d408-467c-8b74-14983569d36c", required = true, value = "Unique reference key for the connection of a loyalty ID and payment card")
  public String getLoyaltyConnectReferenceId() {
    return loyaltyConnectReferenceId;
  }

  public void setLoyaltyConnectReferenceId(String loyaltyConnectReferenceId) {
    this.loyaltyConnectReferenceId = loyaltyConnectReferenceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrollLoyaltyConnectResponse enrollLoyaltyConnectResponse = (EnrollLoyaltyConnectResponse) o;
    return Objects.equals(this.loyaltyConnectReferenceId, enrollLoyaltyConnectResponse.loyaltyConnectReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loyaltyConnectReferenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrollLoyaltyConnectResponse {\n");
    
    sb.append("    loyaltyConnectReferenceId: ").append(toIndentedString(loyaltyConnectReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

