/*
 * Mastercard Loyalty Connect Service
 * Rest Service for linking payment cards with loyalty programme
 *
 * OpenAPI spec version: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MemberMerchantResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-12T16:02:42.822+05:30[Asia/Calcutta]")
public class MemberMerchantResponse {
  public static final String SERIALIZED_NAME_MEMBER_MERCHANT_REFERENCE_ID = "memberMerchantReferenceId";
  @SerializedName(SERIALIZED_NAME_MEMBER_MERCHANT_REFERENCE_ID)
  private String memberMerchantReferenceId;

  public static final String SERIALIZED_NAME_MEMBER_REFERENCE_ID = "memberReferenceId";
  @SerializedName(SERIALIZED_NAME_MEMBER_REFERENCE_ID)
  private String memberReferenceId;

  public MemberMerchantResponse memberMerchantReferenceId(String memberMerchantReferenceId) {
    this.memberMerchantReferenceId = memberMerchantReferenceId;
    return this;
  }

   /**
   * Unique reference key that identifies member and merchant loyalty program association
   * @return memberMerchantReferenceId
  **/
  @ApiModelProperty(example = "3ed6cfa1-f7d9-40ba-9a86-d443ad302ad0", required = true, value = "Unique reference key that identifies member and merchant loyalty program association")
  public String getMemberMerchantReferenceId() {
    return memberMerchantReferenceId;
  }

  public void setMemberMerchantReferenceId(String memberMerchantReferenceId) {
    this.memberMerchantReferenceId = memberMerchantReferenceId;
  }

  public MemberMerchantResponse memberReferenceId(String memberReferenceId) {
    this.memberReferenceId = memberReferenceId;
    return this;
  }

   /**
   * Unique reference key for a member
   * @return memberReferenceId
  **/
  @ApiModelProperty(example = "kT87TFbPtw6z100047", required = true, value = "Unique reference key for a member")
  public String getMemberReferenceId() {
    return memberReferenceId;
  }

  public void setMemberReferenceId(String memberReferenceId) {
    this.memberReferenceId = memberReferenceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberMerchantResponse memberMerchantResponse = (MemberMerchantResponse) o;
    return Objects.equals(this.memberMerchantReferenceId, memberMerchantResponse.memberMerchantReferenceId) &&
        Objects.equals(this.memberReferenceId, memberMerchantResponse.memberReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberMerchantReferenceId, memberReferenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberMerchantResponse {\n");
    
    sb.append("    memberMerchantReferenceId: ").append(toIndentedString(memberMerchantReferenceId)).append("\n");
    sb.append("    memberReferenceId: ").append(toIndentedString(memberReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

