/*
 * Mastercard Loyalty Connect Service
 * Rest Service for linking payment cards with loyalty programme
 *
 * OpenAPI spec version: 1.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaymentCard
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-12T16:02:42.822+05:30[Asia/Calcutta]")
public class PaymentCard {
  public static final String SERIALIZED_NAME_BANK_CARD_NUMBER = "bankCardNumber";
  @SerializedName(SERIALIZED_NAME_BANK_CARD_NUMBER)
  private String bankCardNumber;

  public static final String SERIALIZED_NAME_BANK_CARD_PRODUCT = "bankCardProduct";
  @SerializedName(SERIALIZED_NAME_BANK_CARD_PRODUCT)
  private String bankCardProduct;

  public PaymentCard bankCardNumber(String bankCardNumber) {
    this.bankCardNumber = bankCardNumber;
    return this;
  }

   /**
   * Payment Card number that represents a valid card the MLC user wants to connect
   * @return bankCardNumber
  **/
  @ApiModelProperty(example = "5555555555554444", required = true, value = "Payment Card number that represents a valid card the MLC user wants to connect")
  public String getBankCardNumber() {
    return bankCardNumber;
  }

  public void setBankCardNumber(String bankCardNumber) {
    this.bankCardNumber = bankCardNumber;
  }

  public PaymentCard bankCardProduct(String bankCardProduct) {
    this.bankCardProduct = bankCardProduct;
    return this;
  }

   /**
   * Card product assigned by the Issuer for the payment card
   * @return bankCardProduct
  **/
  @ApiModelProperty(example = "BLACK", value = "Card product assigned by the Issuer for the payment card")
  public String getBankCardProduct() {
    return bankCardProduct;
  }

  public void setBankCardProduct(String bankCardProduct) {
    this.bankCardProduct = bankCardProduct;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentCard paymentCard = (PaymentCard) o;
    return Objects.equals(this.bankCardNumber, paymentCard.bankCardNumber) &&
        Objects.equals(this.bankCardProduct, paymentCard.bankCardProduct);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankCardNumber, bankCardProduct);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentCard {\n");
    
    sb.append("    bankCardNumber: ").append(toIndentedString(bankCardNumber)).append("\n");
    sb.append("    bankCardProduct: ").append(toIndentedString(bankCardProduct)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

